@echo off
REM Push ai-toolbox repo with auto commit message
REM Auto-generated by Claude

set COMMIT_MSG=%~1
if "%COMMIT_MSG%"=="" set COMMIT_MSG=chore: update scripts and tools

cd /d C:\Projects\ai-toolbox
git add .
git commit -m "%COMMIT_MSG%"
git push
echo.
echo ai-toolbox pushed.
timeout /t 3 >nul
